# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Set the version of Python
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
    install:
      - requirements: docs/requirements.txt
