name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                python-version: [3.7.9, 3.8.5, 3.9.0]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              uses: snok/install-poetry@v1
            - name: Install Dependencies
              run: |
                  poetry update
                  poetry install
            - name: Run tests
              run: |
                  pytest -s -vvvv
